# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9594d6a506437946fd55d541b3e73a4c18d0722cebbb5a6ece0a0ba2403716bff4713c046abcdbffef0894014bafeed8a25f358e2e0a3ec7b068251257dad02

test:
  secret_key_base: f9e1cc0425d8074430a195367500a3c66838e2a866c8166241899e3c220992055412c8f461f28ad3e004aed903bd2c50e8f917ec2877981d98a7ce0be0cd6b06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
